2025-07-06 02:50:29,024 : ERROR : Exception on /reset_password_request [POST] [in C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py : 875]
Traceback (most recent call last):
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ~~~~~~~~~~~~~~~~~~~~~^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 941, in finalize_request
    response = self.process_response(response)
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 1322, in process_response
    self.session_interface.save_session(self, ctx.session, response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\sessions.py", line 387, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))  # type: ignore[union-attr]
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\itsdangerous\serializer.py", line 316, in dumps
    payload = want_bytes(self.dump_payload(obj))
                         ~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\itsdangerous\url_safe.py", line 56, in dump_payload
    json = super().dump_payload(obj)
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\itsdangerous\serializer.py", line 278, in dump_payload
    return want_bytes(self.serializer.dumps(obj, **self.serializer_kwargs))
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\tag.py", line 323, in dumps
    return dumps(self.tag(value), separators=(",", ":"))
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\__init__.py", line 41, in dumps
    return current_app.json.dumps(obj, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Kakashi\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Kakashi\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type User is not JSON serializable
2025-07-06 03:41:29,847 : ERROR : Exception on /reset_password_request [POST] [in C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py : 875]
Traceback (most recent call last):
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ~~~~~~~~~~~~~~~~~~~~~^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 941, in finalize_request
    response = self.process_response(response)
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 1322, in process_response
    self.session_interface.save_session(self, ctx.session, response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\sessions.py", line 387, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))  # type: ignore[union-attr]
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\itsdangerous\serializer.py", line 316, in dumps
    payload = want_bytes(self.dump_payload(obj))
                         ~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\itsdangerous\url_safe.py", line 56, in dump_payload
    json = super().dump_payload(obj)
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\itsdangerous\serializer.py", line 278, in dump_payload
    return want_bytes(self.serializer.dumps(obj, **self.serializer_kwargs))
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\tag.py", line 323, in dumps
    return dumps(self.tag(value), separators=(",", ":"))
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\__init__.py", line 41, in dumps
    return current_app.json.dumps(obj, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Kakashi\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Kakashi\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type User is not JSON serializable
2025-07-06 03:55:59,086 : ERROR : Exception on /reset_password_request [POST] [in C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py : 875]
Traceback (most recent call last):
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ~~~~~~~~~~~~~~~~~~~~~^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 941, in finalize_request
    response = self.process_response(response)
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\app.py", line 1322, in process_response
    self.session_interface.save_session(self, ctx.session, response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\sessions.py", line 387, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))  # type: ignore[union-attr]
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\itsdangerous\serializer.py", line 316, in dumps
    payload = want_bytes(self.dump_payload(obj))
                         ~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\itsdangerous\url_safe.py", line 56, in dump_payload
    json = super().dump_payload(obj)
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\itsdangerous\serializer.py", line 278, in dump_payload
    return want_bytes(self.serializer.dumps(obj, **self.serializer_kwargs))
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\tag.py", line 323, in dumps
    return dumps(self.tag(value), separators=(",", ":"))
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\__init__.py", line 41, in dumps
    return current_app.json.dumps(obj, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Kakashi\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Kakashi\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Kakashi\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Kakashi\Desktop\projects\newblog\venv\Lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type User is not JSON serializable
2025-07-07 05:46:07,516 : INFO : Microblog StartUP [in C:\Users\Kakashi\Desktop\projects\newblog\app\__init__.py : 30]
